server:
  port: 6100

#JSP ????
spring:
#  security:
#    user:
#      name: test
#      password: 123
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    username: sa
    password:
  at  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      schema-locations: classpath:h2/schema.sql
      data-locations: classph:h2/data.sql
      encoding: UTF-8
      mode: always

mybatis:
  mapper-locations: classpath:mapper/*_mapper.xml
  configuration:
    map-underscore-to-camel-case: true

